#!/bin/bash
#
# Optional, build-time feature toggles for the Arch image. Everything here is
# OFF by default. The Packer templates expose an enable_<feature> variable
# (each defaulting to false) and map it to the ENABLE_<FEATURE> env vars read
# below, so you turn features on at build time without editing any files:
#
#   make build-qemu NIX=1                 # convenience (Makefile maps NIX -> PKR_VAR)
#   PKR_VAR_enable_nix=true make build    # or set the Packer variable directly
#
# This runs after base.sh, while the freshly installed system is still mounted
# at /mnt, so we configure the target via arch-chroot /mnt.
#
# Adding a new feature (e.g. sbcl + quicklisp):
#   1. declare `variable "enable_sbcl"` in BOTH archbox.pkr.hcl and
#      archbox-qemu.pkr.hcl, and map it in their environment_vars:
#        "ENABLE_SBCL=${var.enable_sbcl ? "1" : ""}"
#   2. add `ENABLE_SBCL="${ENABLE_SBCL:-}"` and a guarded block below
#   3. (optional) add a Makefile convenience like the NIX one

set -euo pipefail

ENABLE_NIX="${ENABLE_NIX:-}"

# base.sh leaves a placeholder /etc/resolv.conf in the target; give the chroot
# working DNS for any package installs here, then restore the placeholder.
restore_resolv_conf() {
  printf '# Generated by resolvconf\n' > /mnt/etc/resolv.conf
}

if [ -n "$ENABLE_NIX" ]; then
  echo "==> Feature: Nix (multi-user daemon + flakes)"

  printf 'nameserver 1.1.1.1\nnameserver 8.8.8.8\n' > /mnt/etc/resolv.conf
  arch-chroot /mnt pacman -S --noconfirm --needed nix

  # Socket-activated daemon for multi-user Nix.
  arch-chroot /mnt systemctl enable nix-daemon.socket

  # Enable flakes and the unified `nix` command system-wide.
  install -d /mnt/etc/nix
  if ! grep -qs '^experimental-features' /mnt/etc/nix/nix.conf; then
    echo 'experimental-features = nix-command flakes' >> /mnt/etc/nix/nix.conf
  fi

  # Let the vagrant user talk to the daemon (group created by the nix package).
  if arch-chroot /mnt getent group nix-users >/dev/null 2>&1; then
    arch-chroot /mnt gpasswd -a vagrant nix-users
  else
    echo "   note: 'nix-users' group not found; skipping group membership" >&2
  fi

  restore_resolv_conf
fi
